// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct CycleInfoData {
  uint256 wisherCount;
  bool isboost;
  uint256 wisherIndexId;
}

library CycleInfo {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "cyberwish", name: "CycleInfo", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746263796265727769736800000000004379636c65496e666f00000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0041030020012000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, uint256, uint256)
  Schema constant _keySchema = Schema.wrap(0x006003005f1f1f00000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, bool, uint256)
  Schema constant _valueSchema = Schema.wrap(0x004103001f601f00000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "poolId";
    keyNames[1] = "cycle";
    keyNames[2] = "boostType";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "wisherCount";
    fieldNames[1] = "isboost";
    fieldNames[2] = "wisherIndexId";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get wisherCount.
   */
  function getWisherCount(
    bytes32 poolId,
    uint256 cycle,
    uint256 boostType
  ) internal view returns (uint256 wisherCount) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get wisherCount.
   */
  function _getWisherCount(
    bytes32 poolId,
    uint256 cycle,
    uint256 boostType
  ) internal view returns (uint256 wisherCount) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set wisherCount.
   */
  function setWisherCount(bytes32 poolId, uint256 cycle, uint256 boostType, uint256 wisherCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((wisherCount)), _fieldLayout);
  }

  /**
   * @notice Set wisherCount.
   */
  function _setWisherCount(bytes32 poolId, uint256 cycle, uint256 boostType, uint256 wisherCount) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((wisherCount)), _fieldLayout);
  }

  /**
   * @notice Get isboost.
   */
  function getIsboost(bytes32 poolId, uint256 cycle, uint256 boostType) internal view returns (bool isboost) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get isboost.
   */
  function _getIsboost(bytes32 poolId, uint256 cycle, uint256 boostType) internal view returns (bool isboost) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set isboost.
   */
  function setIsboost(bytes32 poolId, uint256 cycle, uint256 boostType, bool isboost) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((isboost)), _fieldLayout);
  }

  /**
   * @notice Set isboost.
   */
  function _setIsboost(bytes32 poolId, uint256 cycle, uint256 boostType, bool isboost) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((isboost)), _fieldLayout);
  }

  /**
   * @notice Get wisherIndexId.
   */
  function getWisherIndexId(
    bytes32 poolId,
    uint256 cycle,
    uint256 boostType
  ) internal view returns (uint256 wisherIndexId) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get wisherIndexId.
   */
  function _getWisherIndexId(
    bytes32 poolId,
    uint256 cycle,
    uint256 boostType
  ) internal view returns (uint256 wisherIndexId) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set wisherIndexId.
   */
  function setWisherIndexId(bytes32 poolId, uint256 cycle, uint256 boostType, uint256 wisherIndexId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((wisherIndexId)), _fieldLayout);
  }

  /**
   * @notice Set wisherIndexId.
   */
  function _setWisherIndexId(bytes32 poolId, uint256 cycle, uint256 boostType, uint256 wisherIndexId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((wisherIndexId)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 poolId, uint256 cycle, uint256 boostType) internal view returns (CycleInfoData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 poolId, uint256 cycle, uint256 boostType) internal view returns (CycleInfoData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 poolId,
    uint256 cycle,
    uint256 boostType,
    uint256 wisherCount,
    bool isboost,
    uint256 wisherIndexId
  ) internal {
    bytes memory _staticData = encodeStatic(wisherCount, isboost, wisherIndexId);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 poolId,
    uint256 cycle,
    uint256 boostType,
    uint256 wisherCount,
    bool isboost,
    uint256 wisherIndexId
  ) internal {
    bytes memory _staticData = encodeStatic(wisherCount, isboost, wisherIndexId);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 poolId, uint256 cycle, uint256 boostType, CycleInfoData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.wisherCount, _table.isboost, _table.wisherIndexId);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 poolId, uint256 cycle, uint256 boostType, CycleInfoData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.wisherCount, _table.isboost, _table.wisherIndexId);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 wisherCount, bool isboost, uint256 wisherIndexId) {
    wisherCount = (uint256(Bytes.getBytes32(_blob, 0)));

    isboost = (_toBool(uint8(Bytes.getBytes1(_blob, 32))));

    wisherIndexId = (uint256(Bytes.getBytes32(_blob, 33)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (CycleInfoData memory _table) {
    (_table.wisherCount, _table.isboost, _table.wisherIndexId) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 poolId, uint256 cycle, uint256 boostType) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 poolId, uint256 cycle, uint256 boostType) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 wisherCount, bool isboost, uint256 wisherIndexId) internal pure returns (bytes memory) {
    return abi.encodePacked(wisherCount, isboost, wisherIndexId);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 wisherCount,
    bool isboost,
    uint256 wisherIndexId
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(wisherCount, isboost, wisherIndexId);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 poolId, uint256 cycle, uint256 boostType) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(cycle));
    _keyTuple[2] = bytes32(uint256(boostType));

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
