// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library Props {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "cyberwish", name: "Props", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462637962657277697368000000000050726f70730000000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000100000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, uint256, uint256)
  Schema constant _keySchema = Schema.wrap(0x006003005f1f1f00000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (string)
  Schema constant _valueSchema = Schema.wrap(0x00000001c5000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "poolId";
    keyNames[1] = "boxId";
    keyNames[2] = "id";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "name";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get name.
   */
  function getName(bytes32 poolId, uint256 boxId, uint256 id) internal view returns (string memory name) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get name.
   */
  function _getName(bytes32 poolId, uint256 boxId, uint256 id) internal view returns (string memory name) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get name.
   */
  function get(bytes32 poolId, uint256 boxId, uint256 id) internal view returns (string memory name) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get name.
   */
  function _get(bytes32 poolId, uint256 boxId, uint256 id) internal view returns (string memory name) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set name.
   */
  function setName(bytes32 poolId, uint256 boxId, uint256 id, string memory name) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((name)));
  }

  /**
   * @notice Set name.
   */
  function _setName(bytes32 poolId, uint256 boxId, uint256 id, string memory name) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((name)));
  }

  /**
   * @notice Set name.
   */
  function set(bytes32 poolId, uint256 boxId, uint256 id, string memory name) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((name)));
  }

  /**
   * @notice Set name.
   */
  function _set(bytes32 poolId, uint256 boxId, uint256 id, string memory name) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((name)));
  }

  /**
   * @notice Get the length of name.
   */
  function lengthName(bytes32 poolId, uint256 boxId, uint256 id) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of name.
   */
  function _lengthName(bytes32 poolId, uint256 boxId, uint256 id) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of name.
   */
  function length(bytes32 poolId, uint256 boxId, uint256 id) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of name.
   */
  function _length(bytes32 poolId, uint256 boxId, uint256 id) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of name.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemName(
    bytes32 poolId,
    uint256 boxId,
    uint256 id,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of name.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemName(
    bytes32 poolId,
    uint256 boxId,
    uint256 id,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of name.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(bytes32 poolId, uint256 boxId, uint256 id, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of name.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItem(bytes32 poolId, uint256 boxId, uint256 id, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to name.
   */
  function pushName(bytes32 poolId, uint256 boxId, uint256 id, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to name.
   */
  function _pushName(bytes32 poolId, uint256 boxId, uint256 id, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to name.
   */
  function push(bytes32 poolId, uint256 boxId, uint256 id, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to name.
   */
  function _push(bytes32 poolId, uint256 boxId, uint256 id, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from name.
   */
  function popName(bytes32 poolId, uint256 boxId, uint256 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from name.
   */
  function _popName(bytes32 poolId, uint256 boxId, uint256 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from name.
   */
  function pop(bytes32 poolId, uint256 boxId, uint256 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from name.
   */
  function _pop(bytes32 poolId, uint256 boxId, uint256 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of name at `_index`.
   */
  function updateName(bytes32 poolId, uint256 boxId, uint256 id, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of name at `_index`.
   */
  function _updateName(bytes32 poolId, uint256 boxId, uint256 id, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of name at `_index`.
   */
  function update(bytes32 poolId, uint256 boxId, uint256 id, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of name at `_index`.
   */
  function _update(bytes32 poolId, uint256 boxId, uint256 id, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 poolId, uint256 boxId, uint256 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 poolId, uint256 boxId, uint256 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory name) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(name).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory name) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((name)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(string memory name) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(name);
    bytes memory _dynamicData = encodeDynamic(name);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 poolId, uint256 boxId, uint256 id) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = poolId;
    _keyTuple[1] = bytes32(uint256(boxId));
    _keyTuple[2] = bytes32(uint256(id));

    return _keyTuple;
  }
}
