// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { WishCount } from "./tables/WishCount.sol";
import { WishingPool, WishingPoolData } from "./tables/WishingPool.sol";
import { Wisher, WisherData } from "./tables/Wisher.sol";
import { WisherTemporaryRecords, WisherTemporaryRecordsData } from "./tables/WisherTemporaryRecords.sol";
import { Wishes, WishesData } from "./tables/Wishes.sol";
import { BoostWisherRecords, BoostWisherRecordsData } from "./tables/BoostWisherRecords.sol";
import { CycleInfo, CycleInfoData } from "./tables/CycleInfo.sol";
import { IndexToWisher, IndexToWisherData } from "./tables/IndexToWisher.sol";
import { WisherCycleRecords, WisherCycleRecordsData } from "./tables/WisherCycleRecords.sol";
import { Incense, IncenseData } from "./tables/Incense.sol";
import { PropBlindBox, PropBlindBoxData } from "./tables/PropBlindBox.sol";
import { Props } from "./tables/Props.sol";
