// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IWishSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IWishSystem {
  function cyberwish__wish(
    bytes32 poolId,
    uint256 incenseId,
    uint256 blindBoxId,
    string memory wishContent
  ) external payable;
}
